export const BRAND_GRADIENT = [
  { title: 'Soft Meadow', color: ['#f2f5ed', '#e5eae5'], direction: '135deg', position: 'right' },
  { title: 'Lavender Mist', color: ['#cec5f7', '#f4f7fc'], direction: '135deg' },
  { title: 'Crystal Blue', color: ['#aecdfe', '#d8ecff'], direction: '135deg' },
  { title: 'Dreamy Lilac', color: ['#ebdff8', '#f8fbdc'], direction: '135deg' },
  { title: 'Lime Breeze', color: ['#c8ffc3', '#f5ff6d'], direction: '135deg' },
  { title: 'Pastel Dream', color: ['#f1eaff', '#ffeded'], direction: '135deg' },
  { title: 'Mint Frost', color: ['#cbf4df', '#f0fcf5'], direction: '135deg' },
  { title: 'Sunrise Glow', color: ['#e7f5fd', '#fcebe0'], direction: '135deg', position: 'left' },
  { title: 'Soft Blossom', color: ['#ffe5d3', '#ffe2f0'], direction: '135deg', position: 'right' },
  { title: 'Forest Dawn', color: ['#d4e157', '#388e3c'], direction: '135deg' },
  { title: 'Ocean Breeze', color: ['#00b4db', '#0083b0'], direction: '135deg' },
  { title: 'Sunset Glow', color: ['#ff7e5f', '#feb47b'], direction: '135deg' },
  { title: 'Mountain Mist', color: ['#e0eaf3', '#cfdef3'], direction: '135deg' },
  { title: 'Desert Twilight', color: ['#dae2f8', '#d6a4a4'], direction: '135deg' },
  { title: 'Spring Meadow', color: ['#fdfc47', '#24fe41'], direction: '135deg' },
  { title: 'Glacial Stream', color: ['#83a4d4', '#b6fbff'], direction: '135deg', position: 'left' },
  { title: 'Tropical Paradise', color: ['#43c6ac', '#f8ffae'], direction: '135deg', position: 'right' },
  { title: 'Golden Harvest', color: ['#57370d', '#ffe998'], direction: '135deg' },
  { title: 'Cosmic Dawn', color: ['#6047df', '#e5ccc3'], direction: '135deg' },
  { title: 'Aqua Fresco', color: ['#c1fcd3', '#0ccda3'], direction: '135deg' },
  {title: 'ShadowMauve', color: ['#1e1a2e', '#5c4f6e', '#b3a8c9'], direction: '135deg'},
  {title: 'OysterGlow', color: ['#f8f4f0', '#ddd0c8', '#b0a89f'], direction: '135deg'},
  {title: 'GremeMatcha', color: ['#f5f3ec', '#d2cdb9', '#92a378'], direction: '135deg'},
  {title: 'RustRoseQuartz', color: ['#44291a', '#a15c48', '#f7d6cf'], direction: '135deg', position: 'left' }
];