export const BRAND_GRADIENT = [
  { title: 'Soft Meadow', color: ['#f2f5ed', '#e5eae5'], direction: 'to right', position: 'right' },
  { title: 'Lavender Mist', color: ['#cec5f7', '#f4f7fc'], direction: 'to right' },
  { title: 'Crystal Blue', color: ['#aecdfe', '#d8ecff'], direction: 'to right' },
  { title: 'Dreamy Lilac', color: ['#ebdff8', '#f8fbdc'], direction: 'to right' },
  { title: 'Lime Breeze', color: ['#c8ffc3', '#f5ff6d'], direction: 'to right' },
  { title: 'Pastel Dream', color: ['#f1eaff', '#ffeded'], direction: 'to right' },
  { title: 'Mint Frost', color: ['#cbf4df', '#f0fcf5'], direction: 'to right' },
  { title: 'Sunrise Glow', color: ['#e7f5fd', '#fcebe0'], direction: 'to right', position: 'left' },
  { title: 'Soft Blossom', color: ['#ffe5d3', '#ffe2f0'], direction: 'to right', position: 'right' },
  { title: 'Forest Dawn', color: ['#d4e157', '#388e3c'], direction: 'to right' },
  { title: 'Ocean Breeze', color: ['#00b4db', '#0083b0'], direction: 'to right' },
  { title: 'Sunset Glow', color: ['#ff7e5f', '#feb47b'], direction: 'to right' },
  { title: 'Mountain Mist', color: ['#e0eaf3', '#cfdef3'], direction: 'to right' },
  { title: 'Desert Twilight', color: ['#dae2f8', '#d6a4a4'], direction: 'to right' },
  { title: 'Spring Meadow', color: ['#fdfc47', '#24fe41'], direction: 'to right' },
  { title: 'Glacial Stream', color: ['#83a4d4', '#b6fbff'], direction: 'to right', position: 'left' },
  { title: 'Tropical Paradise', color: ['#43c6ac', '#f8ffae'], direction: 'to right', position: 'right' },
  { title: 'Golden Harvest', color: ['#57370d', '#ffe998'], direction: 'to right' },
  { title: 'Cosmic Dawn', color: ['#6047df', '#e5ccc3'], direction: 'to right' },
  { title: 'Aqua Fresco', color: ['#c1fcd3', '#0ccda3'], direction: 'to right' },
];