export const BRAND_COLORS = [
  { title: 'Cloudy Sky', color: '#ccddea', position: 'right' },
  { title: 'Ocean Blue', color: '#2772a0' },
  { title: 'Soft Sage', color: '#abc8a2' },
  { title: 'Deep Olive', color: '#1a2417' },
  { title: 'Cherry Crush', color: '#e84f5e' },
  { title: 'Peach Cream', color: '#fcdfc5' },
  { title: 'Mint Whisper', color: '#d7eae2' },
  { title: 'Dark Mustard', color: '#4b421b', position: 'left' },
  { title: 'Deep Burgundy', color: '#5c0e14', position: 'right' },
  { title: 'Golden Sand', color: '#f0e193' },
  { title: 'Fresh Lime', color: '#8ed968' },
  { title: 'Evergreen', color: '#103c1f' },
  { title: 'Vanilla Latte', color: '#f3e5c3' },
  { title: 'Teal Forest', color: '#174e4f' },
  { title: 'Platinum', color: '#e2f3f4' },
  { title: 'Photo Blue', color: '#6dc7d1', position: 'left' },
  { title: 'China Rose', color: '#b24c63', position: 'right' },
  { title: 'Palatinate Blue', color: '#5438dc' },
  { title: 'Persian Pink', color: '#f991cc' },
  { title: 'Lavender Pink', color: '#ffdafc' },
  { title: 'Robin Egg Blue', color: '#50c9ce' },
  { title: 'Black Olive', color: '#2e382e' },
  { title: 'White Smoke', color: '#f7f4f3' },
  { title: 'Wine', color: '#5b2333', position: 'left' }
];