export const BRAND_FONTS = {
  'GemarFont': 'GemarFont',
  'HeliosCond': 'HeliosCond',
  'BelbalFont': 'BelbalFont',
  'BelbalFontRegul': 'BelbalFontRegul',
  'FreeSetRegular': 'FreeSetRegular',
  'FreeSetBold': 'FreeSetBold',
  'MyriadPro': 'MyriadPro',
  'RF_Krabuler': 'RF Krabuler',
  'Bosk': 'Bosk',
  'Troubleside': 'Troubleside',
  'Badaboom': 'Badaboom',
  'FuturaRound': 'FuturaRound',
  'FuturaRoundDemi': 'FuturaRoundDemi',
  'RoslinGothic_DG': 'RoslinGothic 👻',
  'Alterna Nr': 'Alterna Nr 👻',
  'Jolly Lodger': 'Jolly Lodger 👻',
  'Swampy': 'Swampy 👻',
  'Magnolia-Script': 'Magnolia 🌷',
  'Lemon Tuesday': 'Lemon 🌷',
  'UniNeueLight': 'Uni Neue 🌷',
  'UniNeueHeavy-Italic': 'Uni Neue Heavy 🌷',
  'NautilusPompilius': 'Nautilus 🌷',
  'Cartonsix NC': 'Cartonsix 🎄',
  'Ice Kingdom': 'Ice Kingdom ⛄🎄',
  'Comic CAT': 'Comic 🎄❤️',
  'Pribambas': 'Pribambas 🎄🌷',
  'VividSans': 'VividSans 🎄',
  'Zametka': 'Zametka 🎄',
  'Kosko': 'Kosko ❤️',
  'Bebas Neue Cyrillic': 'Bebas Neue ⚔️',
  'ft83': 'Русский стиль 🪆',
  'Sunday': 'Русский стиль 2🪆',
  'HeliosCondBlack': 'Helios Cond Black 🎈',
  'Arial': 'Arial',
  'Times New Roman': 'Times New Roman',
  'Verdana': 'Verdana',
  'Georgia': 'Georgia',
  'Courier New': 'Courier New',
  'Calibri': 'Calibri',
  'Tahoma': 'Tahoma',
  'Impact': 'Impact',
  'Comic Sans MS': 'Comic Sans MS',
  'Lucida Sans': 'Lucida Sans',
  'Segoe UI': 'Segoe UI',
  'Cambria': 'Cambria',
  'Garamond': 'Garamond',
  'Franklin Gothic': 'Franklin Gothic',
  'Consolas': 'Consolas',
  'Palatino Linotype': 'Palatino Linotype',
  'Trebuchet MS': 'Trebuchet MS',
  'Book Antiqua': 'Book Antiqua',
  'Century Gothic': 'Century Gothic',
  'Candara': 'Candara'
}