export const PREDEFINED_TAGS = [
  { id: 13, name: 'Фон', color: '#f851f5' },
  { id: 16, name: 'Заголовок', color: '#b786f2' },
  { id: 17, name: 'Иконка', color: '#6bd5f8' },
  { id: 14, name: 'Элемент', color: '#e74f7a' },
  { id: 1, name: 'Belbal', color: '#ea7171' },
  { id: 2, name: 'Gemar', color: '#6de9e1' },
  { id: 3, name: 'Букет', color: '#ebc46a' },
  { id: 18, name: 'Выпускной', color: '#eb7e97' },
  { id: 19, name: 'Я родился', color: '#7aefd0' },
  { id: 20, name: 'Шары', color: '#fb78f9' },
  { id: 21, name: 'Фигура', color: '#b38ce3' },
  { id: 22, name: 'Сервировка', color: '#6ebad3' },
  { id: 23, name: 'ДР', color: '#e06c8d' },
  { id: 4, name: 'С ребенком', color: '#ee8dc7' },
  { id: 5, name: 'В интерьере', color: '#81cbe3' },
  { id: 6, name: 'На природе', color: '#b982dd' },
  { id: 8, name: 'Производство', color: '#77bfd7' },
  { id: 12, name: 'Студия', color: '#7cd9cd' },
  { id: 15, name: 'Пример', color: '#83a2ca' }
];
